fourthpillar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('news.urls')),
    path('tinymce/', include('tinymce.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',Home,name='home' ),
    path('login/',Login,name='login'),
    path('logout/',logoutUser,name='logout'),
    path('register/', register, name="register"),
    path('search/', search,name='search'),
    path('donate/',donate,name='donate' ),
    path('detail/<slug>',detail,name='detail'),
    path('status/<str>',status_news,name='status'),
    path('category/<str>',category,name='category'),
    path('main_category/<str>',main_category,name='main_category'),
    path('tinymce/', include('tinymce.urls')),

    path('addnews/',AddNews,name='addnews'),
    path('add_main_category/',AddMainCategory,name='add_main_category'),
    path('addcategory/<main>',AddCategory,name='addcategory'),
    path('editcategory/<title>',editCategory,name='editcategory'),
    path('edit_main_category/<title>',editMainCategory,name='edit_main_category'),
    path('editnews/<slug>',editNews,name='editnews'),
    path('deletenews/<slug>',delNews,name='deletenews'),
    path('delMainCat/<title>',delMainCat,name='delMainCat'),
    path('delCat/<title>',delCat,name='delCat'),
    path('dashboard/',Admin_panel,name='dashboard'),
    path('admin_news/', Admin_news,name='admin_news'),
    path('admin_category/', Admin_category,name='admin_category'),

    path('donations/', Admin_donation,name='donations'),


    path('videos/', Admin_Videos,name='videos'),
    path('addvideo/',AddVideo,name='addvideo'),
    path('editvideo/<id>',editVideo,name='editvideo'),
    path('delvideo/<id>',delVideos,name='delvideo'),
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

news/models.py
from django.db import models
from autoslug import AutoSlugField
from datetime import datetime
from embed_video.fields import EmbedVideoField
from ckeditor.fields import RichTextField

# Create your models here.


delete_choices= (
    ('deleted','deleted'),
    ('not deleted','not deleted'),

)


class  Main_category(models.Model):
    title=models.CharField(max_length=200,unique=True)
    delete_status = models.CharField(max_length=200, choices=delete_choices, default='not deleted')

    def __str__(self):
        return f'{self.title} '


class  Category(models.Model):
    main_category=models.ForeignKey(Main_category, on_delete=models.CASCADE,null=True,blank=True)
    title=models.CharField(max_length=200,unique=True)
    Image=models.ImageField(upload_to ='media/category',default="media/category/blank.png", null=True, blank=True)
    delete_status = models.CharField(max_length=200, choices=delete_choices, default='not deleted')

    def __str__(self):
        return f'{self.title} '
    

status_choices= (
    ('New','New'),
    ('Most Read','Most Read'),
    ('Trending','Trending')
)
front_choices= (
    ('Show','Show'),
    ('Dont Show','Dont Show'),

)

class latest_news(models.Model):
    category=models.ForeignKey(Category,null=True,blank=True, on_delete=models.SET_NULL)
    title=models.CharField(max_length=200)
    slug= AutoSlugField(populate_from='title',unique=True,null=True,default=None)
    status = models.CharField(max_length=200, choices=status_choices, default='New')
    show_front = models.CharField(max_length=200, choices=front_choices, default='Show')
    delete_status = models.CharField(max_length=200, choices=delete_choices, default='not deleted')
    author=models.CharField(max_length=200,null=True,blank=True)
    Image=models.ImageField(upload_to ='media/%Y/%m/%d/',null=True,blank=True)
    details=RichTextField(blank=True, null=True)
    image_2=models.ImageField(upload_to ='media/%Y/%m/%d/',null=True,blank=True)
    img2_details=RichTextField(blank=True, null=True)
    Image_3=models.ImageField(upload_to ='media/%Y/%m/%d/',null=True,blank=True)
    img3_details=RichTextField(blank=True, null=True)
    date=models.DateTimeField(default=datetime.today)
    # SEO input field.
    meta_title = models.CharField(max_length=120,null=True,blank=True)
    meta_description = models.CharField(max_length=120,null=True,blank=True)
    meta_keyword = models.CharField(max_length=255,null=True,blank=True)


    def __str__(self):
        return f'{self.slug} '



class Videos(models.Model):
    url=EmbedVideoField()
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.url} '


class Donation(models.Model):

    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100 ,null=True,blank=True)
    duration=models.CharField(max_length=10)
    amount=models.IntegerField(null=True,blank=True)
    email=models.EmailField(max_length=100)
    phone=models.CharField(max_length=15)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

news/forms.py
from django.forms import ModelForm
from .models import *
from django import forms


class StylishForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class AddNewsForm(StylishForm):
	class Meta:
		model = latest_news
		exclude =['slug','delete_status','date']
		
	
class CategoryForm(StylishForm):
	class Meta:
		model = Category
		exclude =['delete_status']
		
	
class MainCategoryForm(StylishForm):
	class Meta:
		model = Main_category
		exclude =['delete_status']
		
	
class VideosForm(StylishForm):
	class Meta:
		model = Videos
		fields = '__all__'
		

news/views.py
from django.shortcuts import render,redirect,reverse,get_object_or_404
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User, auth
from .models  import *
from .forms import *
from math import ceil
from django.contrib import messages
from django.db.models import Sum
from django.contrib.auth.decorators import login_required

# Create your views here.


def Home(request):

    if   request.user.is_authenticated:
        return redirect('dashboard')

    else:
        allnews= latest_news.objects.all().order_by('-date').exclude(delete_status='deleted')
        main_cat=Main_category.objects.all()
        new_news= allnews.filter(status='New').exclude(show_front='Dont Show')
        for news in new_news:
            if news.details:
                news.details=re.compile(r'<[^>]+>').sub('', news.details)
                news.details=re.sub("&nbsp;", " ", news.details)
        new1=new_news.first()
        new3=new_news[1:4]

        trending= allnews.filter(status='Trending')
        for news in trending:
            if news.details:
                news.details = re.compile(r'<[^>]+>').sub('', news.details)
                news.details=re.sub("&nbsp;", " ", news.details)
        allvideos=Videos.objects.all().order_by('-date')
        vid1=allvideos.first()
        vid3=allvideos[1:4]


        n= len(allnews)
        nSlides= n//4 + ceil((n/4)-(n//4))
        params = {'no_of_slides':nSlides, 'range': range(1,nSlides),
        'product': allnews,'allnews':allnews,'new1':new1,'new3':new3,
        'main_cat':main_cat,'vid1':vid1,'vid3':vid3, 'trending':trending}

        return render(request,'index.html', params)
import re
import html
def detail(request,slug):
    main_cat=Main_category.objects.all()
    allnews= latest_news.objects.all().order_by('-date').exclude(delete_status='deleted')
    news=latest_news.objects.get(slug=slug)
    author_news=allnews.filter(author=news.author).exclude(slug=slug)[:4]
    new_news= allnews.filter(status='New').exclude(slug=slug)[:3]
    news.details=html.unescape(news.details)
    print(news.details)
    # if news.details:
    #     news.details=re.compile(r'<[^>]+>').sub('', news.details)
    #     news.details=re.sub("&nbsp;", " ", news.details)
    # if news.img2_details:
    #     news.img2_details = re.compile(r'<[^>]+>').sub('', news.img2_details)
    #     news.img2_details=re.sub("&nbsp;", " ", news.img2_details)
    # if news.img3_details:
    #     news.img3_details = re.compile(r'<[^>]+>').sub('', news.img3_details)
    #     news.img3_details=re.sub("&nbsp;", " ", news.img3_details)
    # author_news=re.compile(r'<[^>]+>').sub('', author_news)
    # new_news=re.compile(r'<[^>]+>').sub('', new_news)
    context={'allnews':allnews,'author_news':author_news,'news':news,'new_news':new_news,'main_cat':main_cat}
    return render(request,'detail.html',context)


def status_news(request,str):
    main_cat=Main_category.objects.all()
    allnews= latest_news.objects.all().order_by('-date').exclude(delete_status='deleted')
    news_list=allnews.filter(status=str)
    context={'allnews':allnews,'news_list':news_list,'str':str,'main_cat':main_cat}

    return render(request,'status.html',context)

def main_category(request,str):
    main_cat=Main_category.objects.all()
    main_category=main_cat.get(title=str)
    allnews= latest_news.objects.all().exclude(delete_status='deleted')
    news_list=Category.objects.filter(main_category=main_category)

    context={'allnews':allnews,'news_list':news_list,'str':str,'main_cat':main_cat}

    return render(request,'main_category.html',context)

def category(request,str):
    main_cat=Main_category.objects.all()
    category=Category.objects.get(title=str)
    allnews= latest_news.objects.all().exclude(delete_status='deleted')
    news_list=allnews.filter(category=category)
    context={'allnews':allnews,'news_list':news_list,'str':str,'main_cat':main_cat}

    return render(request,'category.html',context)

def donate(request):
    main_cat=Main_category.objects.all()
    thank=False
    if request.method=="POST":
        first_name = request.POST.get('first_name', '')
        duration = str(request.POST.get('options1'))
        amount = request.POST.get('amount')
        if amount == 'other':
            amount=request.POST.get('amt','')
        last_name = request.POST.get('last_name', '')
        email = request.POST.get('email', '')
        phone1 = str(request.POST.get('phone', ''))
        phone='+91 ' + phone1
        

        try:
            Donation.objects.create(first_name=first_name,last_name=last_name,duration=duration,
            amount=int(amount),email=email,phone=phone)
            thank=True
        
        except:
            print('error submiting')

    return render(request,'donate.html',{'main_cat':main_cat,'thank':thank})


def Login(request):
    if request.user.is_authenticated:
        return redirect('index')
    else:
       if request.method=="POST":
        name=request.POST.get('username')
        pwd=request.POST.get('password')

        user=authenticate(request,username=name,password=pwd)

        if user is not None:
                login(request,user)
                return redirect('home')
        else:
            messages.info(request, 'Username OR Password is incorrect')

    context = {}
    return render(request, 'login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('home')

def search(request):
    
    main_cat=Main_category.objects.all()
    allnews= latest_news.objects.all().exclude(delete_status='deleted')

       
    squery= request.GET.get('search1')
    

    if(squery == '' ):
        squery=0
    
    try:
        news_list=allnews.filter(title__icontains=squery) or allnews.filter(author__icontains=squery)  or allnews.filter(category__icontains=squery) 
    except:
        news_list=None

    context={'news_list':news_list,'str':'Search Result','main_cat':main_cat}
    return render(request,'status.html',context)



@login_required(login_url='login')
def Admin_panel(request):
    allnews= latest_news.objects.all().order_by('-date').exclude(delete_status='deleted')
    navbar = 'dashboard'

    today=datetime.today().date()
    news_today=allnews.filter(date__icontains=today).count()
    total_news=allnews.count()

    donations=Donation.objects.all()

    earn_month=donations.filter(date__icontains=today.strftime("%Y-%m"))
    Earning_monthly=earn_month.aggregate(Sum('amount'))['amount__sum']
    
    earn_year=donations.filter(date__icontains=today.strftime("%Y"))
    Earning_yearly=earn_year.aggregate(Sum('amount'))['amount__sum']

    once=donations.filter(duration='Once').count()
    monthly=donations.filter(duration='Monthly').count()
    yearly=donations.filter(duration='Yearly').count()

    main_cat=Main_category.objects.all().count()
    sub_cat=Category.objects.all().count()

    ylinks=Videos.objects.all().count()

    context={'allnews':allnews,'navbar':navbar,'total_news':total_news,'news_today':news_today,'once':once,
    'monthly':monthly,'yearly':yearly,'Earning_monthly':Earning_monthly,'Earning_yearly':Earning_yearly,'main_cat':main_cat
    ,'sub_cat':sub_cat,'ylinks':ylinks}

    return render(request,'for_admin/admin_panel.html',context)

@login_required(login_url='login')
def Admin_news(request):
    user=request.user
    allnews= latest_news.objects.all().order_by('-date').exclude(delete_status='deleted')
    navbar = 'news'


    form = AddNewsForm()


    if request.method == 'POST':
        form = AddNewsForm(request.POST,instance=user)
        
        if form.is_valid():
            print('valid')


    context={'allnews':allnews,'navbar':navbar,'form':form}
    return render(request,'for_admin/admin_news.html',context)

@login_required(login_url='login')

def delNews(request,slug):

    ednews=latest_news.objects.get(slug=slug)
    ednews.delete_status='deleted'
    ednews.save()

    return redirect('admin_news')

@login_required(login_url='login')

def delMainCat(request,title):

    edcat=Main_category.objects.filter(title=title).delete()
    # edcat.delete_status='deleted'
    # edcat.save()

    return redirect('admin_category')


@login_required(login_url='login')

def delCat(request,title):

    edcat=Category.objects.filter(title=title).delete()
    # edcat.delete_status='deleted'
    # edcat.save()

    return redirect('admin_category')

@login_required(login_url='login')

def AddNews(request):

    page_title='Add News'
    navbar = 'news'
    saveform=False
    ret_url='admin_news'
    form = AddNewsForm()


    if request.method == 'POST':
        form = AddNewsForm(request.POST,request.FILES)
        
        if form.is_valid():

            form.save()
            saveform=True

    context={'navbar':navbar,'form':form,'saveform':saveform,'page_title':page_title,'ret_url':ret_url}
    return render(request,'for_admin/edit_page.html',context)

@login_required(login_url='login')

def editNews(request,slug):

    page_title='Edit News'
    navbar = 'news'
    ret_url='admin_news'
    ednews=latest_news.objects.get(slug=slug)
    saveform=False
    form = AddNewsForm(instance=ednews)


    if request.method == 'POST':
        form = AddNewsForm(request.POST,request.FILES,instance=ednews)
       
        if form.is_valid():

            form.save()
            saveform=True

   

    context={'navbar':navbar, 'form':form,'saveform':saveform,'page_title':page_title,'ret_url':ret_url}
    return render(request,'for_admin/edit_page.html',context)


def register(request):
    # if request.method == 'POST':
    #     username = request.POST['username']
    #     email = request.POST['email']
    #     password1 = request.POST['password1']
    #     passwrod2 = request.POST['password1']

    #     user = User.objects.create_user(username=username, email=email, password=password1)
    #     user.save()
    #     print('user created.')

news/templates/for_admin/addnews.html
{% extends 'for_admin/admin_base.html' %}
{% load static %}
{% block title%} Add News {% endblock %}

{% block body %}


<div class="container">

    <div class="card shadow mb-4 w-75">
        <div class="card-header py-4"> 
    
            <h5 class='d-inline font-weight-bold textred'>Add News:</h5>

        </div>
        <div class="card-body">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form.as_p|safe }}
                <br>
                <div class="modal-footer justify-content-center">
                <input
                class=" text-white btn btn-light red"
                type="submit"
                value="ADD"
                name="addNews"
                style="font-weight: bold;"
                />
                </div>
            </form>
        </div>
    </div>

</div>
<script>


    {% if saveform %}
        alert('News added successfully !');
    
        window.location.href = "{% url 'admin_news' %}";
    {% endif %}


</script>

{% endblock%}

news/templates/for_admin/admin_base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
{% load static %}
<!-- This script got from frontendfreecode.com -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900">
{% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> {% endcomment %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

{% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous"> {% endcomment %}

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
{% comment %} <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> {% endcomment %}
{% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script> {% endcomment %}
{% comment %} <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script> {% endcomment %}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'foradmin.css' %}">
<title>{% block title%} {% endblock %}</title>
<style>

</style>

</head>
<body onload=display_ct();>
<div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar">
        <div class="custom-menu">
            <button type="button" id="sidebarCollapse" class="btn btn-primary">
                <i class="fa fa-bars"></i>
                <span class="sr-only ">Toggle Menu</span>
            </button>
        </div>
        <div class="p-4">
            <h1 class="red rounded-pill" >
                <img class= "rounded-circle border border-light" src="{% static 'logo.png' %}" alt="4thPillar" width='40' height="40">
                <span > 4thPillar </span>
            </h1>
            <hr>
            <ul class="list-unstyled components mb-5">
                <li class="{% if navbar == 'dashboard' %} active {% endif %}">
                    <a href="{% url 'dashboard' %}"> <i class="fas fa-tachometer-alt mx-2"></i>Dashboard</a>
                </li>
                <li class="{% if navbar == 'news' %} active {% endif %}">
                    <a href="{% url 'admin_news' %}"><i class="far fa-newspaper mx-2"></i>News</a>
                </li>
                <li class="{% if navbar == 'category' %} active {% endif %}">
                    <a href="{% url 'admin_category' %}"><i class="fas fa-sitemap mx-2"></i>Categories</a>
                </li>
                <li class="{% if navbar == 'videos' %} active {% endif %}">
                    <a href="{% url 'videos' %}"><i class="fas fa-video mx-2"></i>Youtube Videos</a>
                </li>
                <li class="{% if navbar == 'donations' %} active {% endif %}">
                    <a href="{% url 'donations' %}"><i class="fas fa-hand-holding-usd mx-2"></i> </i>Donations</a>
                </li>


            </ul>

            <span class="d-flex justify-content-center"><a class=" btn btn-secondary red rounded-pill" 
                style="color:white"  href="{% url 'logout' %}"><b><i class="fas fa-sign-out-alt mx-1"></i>Logout</b></a>
            </span>






        </div>
    </nav>

    <!-- Page Content  -->
    <div id="content" >

        <div class="container-fluid p-md-2 " style="box-shadow: 2px 6px 8px 6px rgba(22, 22, 26, 0.18);">

            <div class="d-flex justify-content-end ">
                <p id='dtText'></p>
                <p class="mx-2"> | Logged In as: {{request.user}}</p>
                <span><a  href="{% url 'logout' %}"><b>( <u>Logout </u> )</b></a></span>


            </div>

                <script type="text/javascript"> 
                    function display_c(){
                        var refresh=1000; // Refresh rate in milli seconds
                        mytime=setTimeout('display_ct()',refresh)
                    }
                
                    function display_ct() {
                        var x = new Date()

                        let options = {timeZoneName: 'short',hour:'2-digit',minute:'2-digit',second:'2-digit' ,weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'};
                        
                        var x1=x.toLocaleDateString("en-US", options);
                        document.getElementById('dtText').innerHTML = x1;
                        tt=display_c();
                    }
                </script>  
 
        </div>
        <div class="container-fluid px-4">
            <br><br>
            {% block body %} {% endblock %}
        </div>


    </div>
</div>

<script>
    (function ($) {
        "use strict";
        var fullHeight = function () {
            $(".js-fullheight").css("height", $(window).height());
            $(window).resize(function () {
                $(".js-fullheight").css("height", $(window).height());
            });
        };
        fullHeight();
        $("#sidebarCollapse").on("click", function () {
            $("#sidebar").toggleClass("active");
        });
        
    })(jQuery);




</script>

</body>

<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

</html>

news/templates/for_admin/admin_category.html
{% extends 'for_admin/admin_base.html' %}
{% load static %}
{% block title%} News {% endblock %}

{% block body %}
<div class="container-fluid">
    <div >
        <h2 class='d-inline'>Main Categories :</h2>
        <div class='d-inline mx-5'>
            <a class="btn btn-secondary btn-sm red rounded-pill mb-2" href="{% url 'add_main_category' %}" >
                <i class="fas fa-plus-circle"></i><b> Add New </b></a>
            </a>
        </div>
    </div>
    <hr>

    {%for mc in main_cat%}
    {% if mc.delete_status == 'not deleted' %}
    <div class="card shadow mb-4">
        <div class="card-header py-4"> 
    
            <h5 class='d-inline font-weight-bold textred'>{{mc.title}} : 
                <span  class="mx-5" >
                    <a title="Edit" class="btn-sm yellow mb-2" href="{% url 'edit_main_category' mc.title %}" ><i class="fas fa-pen"></i></a>
                    <a title="Delete " class="btn-sm btn-danger mb-2" href="{% url 'delMainCat' mc.title %}" onclick="return confirm('Are you sure you want to delete this item?');"><i class="fas fa-trash-alt"></i></a>
                </span>
            </h5>
            
            <div class='d-inline mr-3 'style="position: absolute; right: 0;">
                <a class="btn btn-secondary btn-sm red rounded-pill mb-2" href="{% url 'addcategory' mc.title %}" >
                    <i class="fas fa-plus-circle"></i><b> Add New </b></a>
                </a>
            </div>
            
            
        </div>
        {%if mc.category_set.all%}

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="NewsTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Sr.No.</th>
                            <th>Image:</th>
                            <th>Title:</th>
                            <th>Action:</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        {%for sub in mc.category_set.all%}

                        {% if sub.delete_status == 'not deleted' %}
                            <tr>

                                <td width="1%">{{ forloop.counter }}</td>
                                <td width="5%">
                                    {% if sub.Image %}
                                    <img src="{{sub.Image.url}}" height='70' width='100' alt='...'>
                                    {%endif%}
                                </td>
                                <td width="20%"><span class="slc3">{{sub.title}} </span></td>
                                <td width="1%" >
                                    <a title="Edit" class="btn-sm yellow mb-2" href="{% url 'editcategory' sub.title %}" ><i class="fas fa-pen"></i></a>
                                    <a title="Delete " class="btn-sm btn-danger mb-2" href="{% url 'delCat' sub.title %}" onclick="return confirm('Are you sure you want to delete this item?');"><i class="fas fa-trash-alt"></i></a>
                                </td>

                            </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {%endif%}
    </div>
    {%endif%}
    {%endfor%}

</div>

<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css">

<script>

    $(document).ready(function() {
        $('#NewsTable').dataTable();
    });
    
</script>

{%endblock%}

news/templates/for_admin/admin_donation.html
{% extends 'for_admin/admin_base.html' %}
{% load static %}
{% block title%} Donations {% endblock %}

{% block body %}

<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-4"> 
    
            <h5 class='d-inline font-weight-bold textred'>Donations:</h5>
            
            
            
        </div>
    
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="donationTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Sr.No.</th>
                            <th>Name:</th>
                            <th>Amount</th>
                            <th>Email</th>
                            <th>Contact Number</th>
                            <th>Date</th>

                            
                        </tr>
                    </thead>
                    <tbody>

                   {% for dn in alldonate %}
        
                            <tr>
                                <td width="1%">{{ forloop.counter }}</td>
                                <td >{{dn.first_name}} {{dn.last_name}}</td>
                                <td><b>₹ {{dn.amount}} / {{dn.duration}}</b></td>
                                <td>{{dn.email}} </td>
                                <td>{{dn.phone}} </td>
                                <td width="10%">{{dn.date}}</td>


                            </tr> 
                            
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>       
    </div>
    
</div>

<br>

<!-- Page level plugins -->

<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css" >

<script>

    $(document).ready(function() {
        $('#donationTable').dataTable();
    } );
    
</script>

{% endblock%}

news/templates/for_admin/edit_page.html
{% extends 'for_admin/admin_base.html' %}
{% load static %}
{% block title%} {{page_title}} {% endblock %}

{% block body %}


<div class="container">

    <div class="card shadow mb-4 w-75">
        <div class="card-header py-4"> 
    
            <h5 class='d-inline font-weight-bold textred'>{{page_title}}:</h5>

        </div>
        <div class="card-body">
            <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %} {{form.as_p}}
                <br>
                <div class="modal-footer justify-content-center">
                <input
                class=" text-white btn btn-light red"
                type="submit"
                value="Save"
                name="SaveNews"
                style="font-weight: bold;"
                />
                </div>
            </form>
        </div>
    </div>

</div>
<script>


    {% if saveform %}
        alert('Saved successfully !');
    
        window.location.href = "{% url ret_url %}";
    {% endif %}


</script>

{% endblock%}